use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :elixir_jobs, ElixirJobsWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [npm: ["run", "watch", "--stdin", cd: Path.expand("../assets/", __DIR__)]]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :elixir_jobs, ElixirJobsWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/elixir_jobs_web/views/.*(ex)$},
      ~r{lib/elixir_jobs_web/templates/.*(eex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# BCrypt configuration
config :bcrypt_elixir, :log_rounds, 10

config :elixir_jobs, ElixirJobsWeb.Guardian,
  issuer: "ElixirJobs",
  secret_key: "MY_D3V_K3Y"

config :elixir_jobs, ElixirJobsWeb.Mailer, adapter: Bamboo.LocalAdapter

config :elixir_jobs, :default_app_email, "no-reply@elixirjobs.net"
config :elixir_jobs, :analytics_id, ""
config :elixir_jobs, :telegram_channel, "elixir_jobs_st"

# Import custom configuration
import_config "dev.secret.exs"
