import Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# ElixirJobsWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :elixir_jobs, ElixirJobsWeb.Endpoint,
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# BCrypt configuration
config :bcrypt_elixir, :log_rounds, 10

config :elixir_jobs, :default_app_email, "no-reply@elixirjobs.net"
config :elixir_jobs, :analytics_id, "UA-106824960-1"
config :elixir_jobs, :telegram_channel, "elixir_jobs"

# AppSignal
config :appsignal, :config, active: true
